In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [4]:
RNA_path = Path("rna-cna-breast-cancer-analysis/data/raw/brca_tcga_pan_can_atlas_2018/data_mrna_seq_v2_rsem.txt")
RNA_dataset = pd.read_csv(RNA_path, sep="\t", encoding="utf-8")

#dataset structure
RNA_dataset.head()

,Hugo_Symbol,Entrez_Gene_Id,TCGA-3C-AAAU-01,TCGA-3C-AALI-01,TCGA-3C-AALJ-01,TCGA-3C-AALK-01,TCGA-4H-AAAK-01,TCGA-5L-AAT0-01,TCGA-5T-A9QA-01,TCGA-A1-A0SB-01,...,TCGA-UL-AAZ6-01,TCGA-UU-A93S-01,TCGA-V7-A7HQ-01,TCGA-W8-A86G-01,TCGA-WT-AB41-01,TCGA-WT-AB44-01,TCGA-XX-A899-01,TCGA-XX-A89A-01,TCGA-Z7-A8R5-01,TCGA-Z7-A8R6-01
0,NaN,100130426,0.0000,0.0000,0.9066,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,NaN,100133144,16.3644,9.2659,11.6228,12.0894,6.8468,3.9889,1.4644,15.3396,...,0.3992,4.3126,0.0000,5.5624,0.0000,0.0000,14.3858,22.3240,2.2638,6.8865
2,UBE2Q2P2,100134869,12.9316,17.3790,9.2294,11.0799,14.4298,13.6090,8.9958,14.3935,...,14.3720,10.8828,3.0792,14.3711,6.3091,3.2580,21.4409,27.2744,7.2933,24.7795
3,HMGB1P1,10357,52.1503,69.7553,154.2970,143.8640,84.2128,114.2570,107.5630,116.3870,...,135.6240,136.1290,29.9974,128.3150,53.6278,42.2643,137.7760,64.1427,85.0461,167.5510
4,NaN,10431,408.0760,563.8930,1360.8300,865.5360,766.3830,807.7430,1420.5000,657.2810,...,1570.1400,2886.4000,1721.8800,697.6740,1245.2700,1877.4200,652.7560,722.7210,1140.2800,1003.5700

In [5]:
print(f"Number of rows and columns: {RNA_dataset.shape}")
RNA_dataset.info()

Number of rows and columns: (20531, 1084)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20531 entries, 0 to 20530
Columns: 1084 entries, Hugo_Symbol to TCGA-Z7-A8R6-01
dtypes: float64(1082), int64(1), object(1)
memory usage: 169.8+ MB

In [6]:
#Structure evaluation 
RNA_dataset.iloc[:5, :6]

,Hugo_Symbol,Entrez_Gene_Id,TCGA-3C-AAAU-01,TCGA-3C-AALI-01,TCGA-3C-AALJ-01,TCGA-3C-AALK-01
0,NaN,100130426,0.0000,0.0000,0.9066,0.0000
1,NaN,100133144,16.3644,9.2659,11.6228,12.0894
2,UBE2Q2P2,100134869,12.9316,17.3790,9.2294,11.0799
3,HMGB1P1,10357,52.1503,69.7553,154.2970,143.8640
4,NaN,10431,408.0760,563.8930,1360.8300,865.5360

In [7]:
genes = RNA_dataset[["Hugo_Symbol", "Entrez_Gene_Id"]].copy()
RNA_expresion = RNA_dataset.iloc[:, 2:].copy()

In [9]:
# Tipos de datos de las columnas de expresión
print(RNA_expresion.dtypes.value_counts())
# Número total de mediciones ausentes
print(RNA_expresion.isna().sum().sum())
# Ausencias en los identificadores
print(genes.isna().sum())
# Identificadores Entrez repetidos
print(genes["Entrez_Gene_Id"].duplicated().sum())

float64    1082
Name: count, dtype: int64
0
Hugo_Symbol       13
Entrez_Gene_Id     0
dtype: int64
26